version: 2.1

description: >
  Split circle configuration across monorepo packages and skip jobs for packages that did not change

executors:
  circletron-executor:
    docker:
      - image: ghcr.io/1024pix/circletron:npm

jobs:
  trigger-jobs:
    executor: circletron-executor
    steps:
      - checkout
      - run:
          name: trigger jobs
          command: circletron
